---
- hosts: db
  become: yes
  tasks:
    - name: "Instação de Pacote na Máquina DB"
      apt: 
        pkg: 
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present

    - name: "Baixar e Extrair arquivo db.zip"
      unarchive: 
        src: https://github.com/rogerramossilva/devops/raw/master/db.zip
        dest: /tmp
        remote_src: yes

    - name: "Criação de Banco de dados Backup"
      mysql_db:
        name: backup
        login_user: root
        login_password: ''
        state: present

    - name: "Importação do BD backup.sql"
      mysql_db: 
        name: backup
        login_user: root
        login_password: ""
        state: import
        target: /tmp/backup.sql 

    - name: "Criar e concer privilégos para usuário express"
      mysql_user:
        host: '%'
        login_user: root
        login_password: ""
        name: express
        password: "AllSafe0!"
        priv: 'backup.*:ALL'
        state: present
    - name: "Liberar porta do mysql" 
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart Mysql

  handlers:
    - name: Restart Mysql
      service:
        name: mysql
        state: restarted
        enabled: yes